apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gemfire-management-console-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 4Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: gemfire-management-console
    run:  gemfire-management-console
  name:  gemfire-management-console
spec:
  replicas: 1
  selector:
    matchLabels:
      name:  gemfire-management-console
  template:
    metadata:
      labels:
        name:  gemfire-management-console
    spec:
      containers:
        - env:
            - name: server.port
              value: "8080"
          image: gemfire/gemfire-management-console:1.3.1
          name: gemfire-management-console
          imagePullPolicy: IfNotPresent
#      volumes:
#        - name: gemfire-management-console-persistence
#          persistentVolumeClaim:
#            claimName: gemfire-management-console-pvc
#          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: gemfire-management-console
spec:
  selector:
    name: gemfire-management-console
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer